trigger: none

pr:
  branches:
    include:
      - main

parameters:
  - name: folderName
    displayName: "Select Terraform Folder"
    type: string
    default: "connected_online"
    values:
      - "firewall_bastion_hub"
      - "cloud_exclusive"
      - "cloud_exclusive_online"
      - "connected"
      - "connected_online"
      - "isolated"
      - "isolated_online"

variables:
  - group: TerraformSecrets  # Reference stored secrets in ADO

stages:
  - stage: Terraform_Import
    displayName: "Import Existing Resources"
    jobs:
      - job: Terraform_Import_Resources
        displayName: "Import Existing Resource Group into Terraform"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.9.2'

          - script: |
              cd $(Build.SourcesDirectory)/${{ parameters.folderName }}
              terraform init -input=false \
                -backend-config="resource_group_name=rg-dev-001" \
                -backend-config="storage_account_name=tfstatedemonew" \
                -backend-config="container_name=tfstate" \
                -backend-config="key=${{ parameters.folderName }}.tfstate" \
                -backend-config="use_azuread_auth=true"
            displayName: "Terraform Init"

          - script: |
              cd $(Build.SourcesDirectory)/${{ parameters.folderName }}

              echo "Checking if resource group is already in Terraform state..."
              terraform state list | grep azurerm_resource_group.this

              if [ $? -ne 0 ]; then
                echo "Resource group not in state. Importing..."
                terraform import azurerm_resource_group.this /subscriptions/$(ARM_SUBSCRIPTION_ID)/resourceGroups/rg-dev-002
              else
                echo "Resource group already in Terraform state. Skipping import."
              fi
            displayName: "Import Resource Group If Needed"
            env:
              ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
              ARM_CLIENT_SECRET: "$(ARM_CLIENT_SECRET)"
              ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
              ARM_TENANT_ID: "$(ARM_TENANT_ID)"

  - stage: Terraform
    jobs:
      - job: RunTerraform
        steps:
          - checkout: self

          - script: |
              echo "Checking folder existence at $(Build.SourcesDirectory)/${{ parameters.folderName }}"
              if [ -d "$(Build.SourcesDirectory)/${{ parameters.folderName }}" ]; then
                echo "Folder exists!"
              else
                echo "Error: Folder does not exist!"
                exit 1
              fi
            displayName: "Verify Folder Exists"

  - stage: Terraform_Deployment
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform_Deploy
        displayName: "Deploy Terraform"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.9.2'

          - script: |
              cd $(Build.SourcesDirectory)/${{ parameters.folderName }}
            displayName: "Change Directory to Selected Folder"

          - task: AzureCLI@2
            displayName: "Terraform Init"
            inputs:
              azureSubscription: "Terraform Deployment Connection_1"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                cd $(Build.SourcesDirectory)/${{ parameters.folderName }}
                terraform init -input=false \
                  -backend-config="resource_group_name=rg-dev-001" \
                  -backend-config="storage_account_name=tfstatedemonew" \
                  -backend-config="container_name=tfstate" \
                  -backend-config="key=${{ parameters.folderName }}.tfstate" \
                  -backend-config="use_azuread_auth=true"
            env:
              ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
              ARM_CLIENT_SECRET: "$(ARM_CLIENT_SECRET)"
              ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
              ARM_TENANT_ID: "$(ARM_TENANT_ID)"

          - script: |
              cd $(Build.SourcesDirectory)/${{ parameters.folderName }}
              terraform validate
            displayName: "Terraform Validate"

          - task: AzureCLI@2
            displayName: "Terraform Plan"
            inputs:
              azureSubscription: "Terraform Deployment Connection_1"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                cd $(Build.SourcesDirectory)/${{ parameters.folderName }}
                terraform plan -out=tfplan -input=false
            env:
              ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
              ARM_CLIENT_SECRET: "$(ARM_CLIENT_SECRET)"
              ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
              ARM_TENANT_ID: "$(ARM_TENANT_ID)"

          - task: AzureCLI@2
            displayName: "Terraform Apply"
            inputs:
              azureSubscription: "Terraform Deployment Connection_1"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                cd $(Build.SourcesDirectory)/${{ parameters.folderName }}
                terraform apply -auto-approve tfplan
            env:
              ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
              ARM_CLIENT_SECRET: "$(ARM_CLIENT_SECRET)"
              ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
              ARM_TENANT_ID: "$(ARM_TENANT_ID)"
