trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_SUBSCRIPTION: 'Terraform Deployment Connection'  # Replace with your service connection name
  TF_VERSION: '1.9.2'  # Specify Terraform version
  RESOURCE_GROUP: 'rg-dev-001'
  STORAGE_ACCOUNT: 'tfstatedemonew'
  CONTAINER_NAME: 'tfstate'
  LOCATION: 'Canada Central'

steps:
  # Step 1: Install Terraform
  - task: TerraformInstaller@1
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: $(TF_VERSION)

  # Step 2: Login to Azure using Managed Identity
  - task: AzureCLI@2
    displayName: 'Login to Azure using Managed Identity'
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Logging into Azure using Managed Identity..."
        az login --identity
        az account show

  

  # Step 3: Terraform Init with Managed Identity
  - task: AzureCLI@2
    displayName: "Terraform Init"
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        terraform init -input=false \
          -backend-config="resource_group_name=$(RESOURCE_GROUP)" \
          -backend-config="storage_account_name=$(STORAGE_ACCOUNT)" \
          -backend-config="container_name=$(CONTAINER_NAME)" \
          -backend-config="key=terraform.tfstate"
    env:
      ARM_USE_MSI: true
      ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"   # Managed Identity Client ID
      ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
      ARM_TENANT_ID: "$(ARM_TENANT_ID)"

  # Step 4: Terraform Validate
  - task: AzureCLI@2
    displayName: "Terraform Validate"
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        terraform validate

  # Step 5: Terraform Plan
  - task: AzureCLI@2
    displayName: "Terraform Plan"
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        terraform plan -out=tfplan -input=false

  # Step 6: Terraform Apply (Only on main branch and if plan file exists)
  - task: AzureCLI@2
    displayName: "Terraform Apply"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        if [ -f tfplan ]; then
          terraform apply -auto-approve tfplan
        else
          echo "Terraform plan file not found. Skipping apply."
          exit 1
        fi
 