trigger:
   branches:
     include:
       - main
 
pr:
   branches:
     include:
       - main
 
variables:
   - group: Terraformsecrets  # Reference stored secrets in ADO
 
stages:
   - stage: Terraform_Deployment
     displayName: "Terraform Deployment"
     jobs:
       - job: Terraform_Deploy
         displayName: "Deploy Terraform"
         pool:
           vmImage: 'ubuntu-latest'
         steps:
           - checkout: self

           # Install Terraform
           - task: TerraformInstaller@1
             displayName: "Install Terraform"
             inputs:
               terraformVersion: '1.9.2'

           # Fetch OIDC Token
           - task: AzureCLI@2
             displayName: "Fetch OIDC Token"
             inputs:
              azureSubscription: "Terraform Deployment Connection"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                echo "Fetching OIDC Token..."
                export ARM_OIDC_TOKEN=$(az account get-access-token --resource https://management.azure.com --query accessToken --output tsv)

                if [ -z "$ARM_OIDC_TOKEN" ]; then
                  echo "Error: Failed to retrieve OIDC Token!"
                  exit 1
                fi

                echo "OIDC Token fetched successfully!"
                echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN;]$ARM_OIDC_TOKEN"
                echo "##vso[task.setvariable variable=ARM_USE_OIDC;]true"

                # Set other environment variables from Azure DevOps secrets
                echo "##vso[task.setvariable variable=ARM_TENANT_ID;]$(TENANT_ID)"
                echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;]$(SUBSCRIPTION_ID)"
                echo "##vso[task.setvariable variable=ARM_CLIENT_ID;]$(SERVICE_PRINCIPAL_ID)"

           # Debug Azure Authentication
           - task: AzureCLI@2
             displayName: "Debug Azure Authentication"
             inputs:
              azureSubscription: "Terraform Deployment Connection"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                echo "Checking Azure authentication..."
                az account show --output table || echo "Failed to authenticate!"
                az account get-access-token --resource https://management.azure.com || echo "Failed to fetch token!"

           # Terraform Init
           - script: |
               terraform init -input=false
             displayName: "Terraform Init"
             env:
               ARM_USE_OIDC: "true"
               ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
               ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
               ARM_TENANT_ID: "$(ARM_TENANT_ID)"
               ARM_OIDC_TOKEN: "$(ARM_OIDC_TOKEN)"

           # Terraform Validate
           - script: |
               terraform validate
             displayName: "Terraform Validate"

           # Terraform Plan
           - task: AzureCLI@2
             displayName: "Terraform Plan"
             inputs:
               azureSubscription: "Terraform Deployment Connection"
               scriptType: "bash"
               scriptLocation: "inlineScript"
               inlineScript: |
                 terraform plan -out=tfplan -input=false 

           # Terraform Apply
           - task: AzureCLI@2
             displayName: "Terraform Apply"
             inputs:
               azureSubscription: "Terraform Deployment Connection"
               scriptType: "bash"
               scriptLocation: "inlineScript"
               inlineScript: |
                 terraform apply -auto-approve tfplan  
