trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  - group: TerraformSecrets  # Reference stored secrets in ADO

stages:
  - stage: Terraform_Deployment
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform_Deploy
        displayName: "Deploy Terraform"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          # Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.9.2'

          # Retrieve OIDC Token
          - task: AzureCLI@2
            displayName: "Retrieve OIDC Token"
            inputs:
              azureSubscription: "Terraform Deployment Connection"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                echo "Fetching OIDC Token..."
                export ARM_TENANT_ID="$(ARM_TENANT_ID)"
                export ARM_CLIENT_ID="$(ARM_CLIENT_ID)"
                export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"
                export ARM_OIDC_TOKEN=$(curl -sSL -H "Authorization: Bearer $(System.AccessToken)" \
                  --request GET \
                  "https://management.azure.com/.default" | jq -r '.access_token')

                if [ -z "$ARM_OIDC_TOKEN" ]; then
                  echo "Error: Failed to retrieve OIDC token"
                  exit 1
                fi

                echo "OIDC Token successfully retrieved."

          # Terraform Init
          - script: |
              terraform init -input=false
            displayName: "Terraform Init"
            env:
              ARM_USE_OIDC: true
              ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
              ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
              ARM_TENANT_ID: "$(ARM_TENANT_ID)"
              ARM_OIDC_TOKEN: "$(ARM_OIDC_TOKEN)"

          # Terraform Validate (Checks syntax and configuration before applying)
          - script: |
              terraform validate
            displayName: "Terraform Validate"

          # Terraform Plan
          - script: |
              terraform plan -out=tfplan -input=false
            displayName: "Terraform Plan"
            env:
              ARM_USE_OIDC: true
              ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
              ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
              ARM_TENANT_ID: "$(ARM_TENANT_ID)"
              ARM_OIDC_TOKEN: "$(ARM_OIDC_TOKEN)"

          # Terraform Apply (only on main branch and if plan file exists)
          - script: |
              if [ -f "tfplan" ]; then
                terraform apply -auto-approve tfplan
              else
                echo "Terraform plan file not found. Skipping apply."
                exit 1
              fi
            displayName: "Terraform Apply"
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
            env:
              ARM_USE_OIDC: true
              ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
              ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
              ARM_TENANT_ID: "$(ARM_TENANT_ID)"
              ARM_OIDC_TOKEN: "$(ARM_OIDC_TOKEN)"